// Code generated by re2c 2.2 on Mon Dec 20 14:32:01 2021, DO NOT EDIT.
package lexer

import "bytes"
import "github.com/masp/hoser/token"

func (s *Scanner) lex() (pos token.Pos, tok token.Token, lit string, err error) {
	for {
		lit = ""
		pos = s.pos()
		s.token = s.cursor

		{
			var yych byte
			yyaccept := 0
			yych = s.text[s.cursor]
			if yych <= '9' {
				if yych <= '"' {
					if yych <= '\f' {
						if yych <= 0x08 {
							if yych >= 0x01 {
								goto yy4
							}
						} else {
							if yych <= '\t' {
								goto yy6
							}
							if yych <= '\n' {
								goto yy9
							}
							goto yy4
						}
					} else {
						if yych <= 0x1F {
							if yych <= '\r' {
								goto yy11
							}
							goto yy4
						} else {
							if yych <= ' ' {
								goto yy6
							}
							if yych <= '!' {
								goto yy4
							}
							goto yy12
						}
					}
				} else {
					if yych <= '+' {
						if yych <= '\'' {
							if yych <= '#' {
								goto yy14
							}
							goto yy4
						} else {
							if yych <= '(' {
								goto yy17
							}
							if yych <= ')' {
								goto yy19
							}
							goto yy4
						}
					} else {
						if yych <= '.' {
							if yych <= ',' {
								goto yy21
							}
							if yych <= '-' {
								goto yy4
							}
							goto yy23
						} else {
							if yych <= '/' {
								goto yy4
							}
							if yych <= '0' {
								goto yy25
							}
							goto yy26
						}
					}
				}
			} else {
				if yych <= 'l' {
					if yych <= '@' {
						if yych <= ';' {
							if yych <= ':' {
								goto yy29
							}
							goto yy31
						} else {
							if yych == '=' {
								goto yy33
							}
							goto yy4
						}
					} else {
						if yych <= '^' {
							if yych <= 'Z' {
								goto yy35
							}
							goto yy4
						} else {
							if yych == '`' {
								goto yy4
							}
							goto yy35
						}
					}
				} else {
					if yych <= 'r' {
						if yych <= 'o' {
							if yych <= 'm' {
								goto yy38
							}
							goto yy35
						} else {
							if yych <= 'p' {
								goto yy39
							}
							if yych <= 'q' {
								goto yy35
							}
							goto yy40
						}
					} else {
						if yych <= '{' {
							if yych <= 's' {
								goto yy41
							}
							if yych <= 'z' {
								goto yy35
							}
							goto yy42
						} else {
							if yych == '}' {
								goto yy44
							}
							goto yy4
						}
					}
				}
			}
			s.cursor += 1
			{
				tok = token.Eof
				return
			}
		yy4:
			s.cursor += 1
		yy5:
			{
				err = ErrBadToken
				return
			}
		yy6:
			s.cursor += 1
			yych = s.text[s.cursor]
			if yych == '\t' {
				goto yy6
			}
			if yych == ' ' {
				goto yy6
			}
			{
				continue
			}
		yy9:
			s.cursor += 1
			{
				if s.insertSemi() {
					s.cursor = s.token // Has the effect of "inserting" the semicolon in the input
					tok = token.Semicolon
					lit = "\n"
					return
				} else {
					s.file.AddLine(s.token)
					continue
				}
			}
		yy11:
			s.cursor += 1
			yych = s.text[s.cursor]
			if yych == '\n' {
				goto yy9
			}
			goto yy5
		yy12:
			s.cursor += 1
			{
				return s.lexString('"')
			}
		yy14:
			s.cursor += 1
			yych = s.text[s.cursor]
			if yych <= '\n' {
				if yych <= 0x00 {
					goto yy16
				}
				if yych <= '\t' {
					goto yy14
				}
			} else {
				if yych != '\r' {
					goto yy14
				}
			}
		yy16:
			{
				tok = token.Comment
				lit = s.literal()
				return
			}
		yy17:
			s.cursor += 1
			{
				tok = token.LParen
				lit = "("
				return
			}
		yy19:
			s.cursor += 1
			{
				tok = token.RParen
				lit = ")"
				return
			}
		yy21:
			s.cursor += 1
			{
				tok = token.Comma
				lit = ","
				return
			}
		yy23:
			s.cursor += 1
			yych = s.text[s.cursor]
			if yych <= '/' {
				goto yy24
			}
			if yych <= '9' {
				goto yy46
			}
		yy24:
			{
				tok = token.Period
				lit = "."
				return
			}
		yy25:
			yyaccept = 0
			s.cursor += 1
			s.marker = s.cursor
			yych = s.text[s.cursor]
			if yych <= '9' {
				if yych == '.' {
					goto yy46
				}
				if yych <= '/' {
					goto yy5
				}
				goto yy49
			} else {
				if yych <= 'E' {
					if yych <= 'D' {
						goto yy5
					}
					goto yy52
				} else {
					if yych == 'e' {
						goto yy52
					}
					goto yy5
				}
			}
		yy26:
			yyaccept = 1
			s.cursor += 1
			s.marker = s.cursor
			yych = s.text[s.cursor]
			if yych <= '9' {
				if yych == '.' {
					goto yy46
				}
				if yych >= '0' {
					goto yy26
				}
			} else {
				if yych <= 'E' {
					if yych >= 'E' {
						goto yy52
					}
				} else {
					if yych == 'e' {
						goto yy52
					}
				}
			}
		yy28:
			{
				tok = token.Integer
				lit = s.literal()
				return
			}
		yy29:
			s.cursor += 1
			{
				tok = token.Colon
				lit = ":"
				return
			}
		yy31:
			s.cursor += 1
			{
				tok = token.Semicolon
				lit = ";"
				return
			}
		yy33:
			s.cursor += 1
			{
				tok = token.Equals
				lit = "="
				return
			}
		yy35:
			s.cursor += 1
			yych = s.text[s.cursor]
		yy36:
			if yych <= 'Z' {
				if yych <= '/' {
					goto yy37
				}
				if yych <= '9' {
					goto yy35
				}
				if yych >= 'A' {
					goto yy35
				}
			} else {
				if yych <= '_' {
					if yych >= '_' {
						goto yy35
					}
				} else {
					if yych <= '`' {
						goto yy37
					}
					if yych <= 'z' {
						goto yy35
					}
				}
			}
		yy37:
			{
				tok = token.Ident
				lit = s.literal()
				return
			}
		yy38:
			s.cursor += 1
			yych = s.text[s.cursor]
			if yych == 'o' {
				goto yy53
			}
			goto yy36
		yy39:
			s.cursor += 1
			yych = s.text[s.cursor]
			if yych == 'i' {
				goto yy54
			}
			goto yy36
		yy40:
			s.cursor += 1
			yych = s.text[s.cursor]
			if yych == 'e' {
				goto yy55
			}
			goto yy36
		yy41:
			s.cursor += 1
			yych = s.text[s.cursor]
			if yych == 't' {
				goto yy56
			}
			goto yy36
		yy42:
			s.cursor += 1
			{
				tok = token.LCurlyBrack
				lit = "{"
				return
			}
		yy44:
			s.cursor += 1
			{
				tok = token.RCurlyBrack
				lit = "}"
				return
			}
		yy46:
			yyaccept = 2
			s.cursor += 1
			s.marker = s.cursor
			yych = s.text[s.cursor]
			if yych <= 'D' {
				if yych <= '/' {
					goto yy48
				}
				if yych <= '9' {
					goto yy46
				}
			} else {
				if yych <= 'E' {
					goto yy52
				}
				if yych == 'e' {
					goto yy52
				}
			}
		yy48:
			{
				tok = token.Float
				lit = s.literal()
				return
			}
		yy49:
			s.cursor += 1
			yych = s.text[s.cursor]
			if yych <= '9' {
				if yych == '.' {
					goto yy46
				}
				if yych >= '0' {
					goto yy49
				}
			} else {
				if yych <= 'E' {
					if yych >= 'E' {
						goto yy52
					}
				} else {
					if yych == 'e' {
						goto yy52
					}
				}
			}
		yy51:
			s.cursor = s.marker
			if yyaccept <= 1 {
				if yyaccept == 0 {
					goto yy5
				} else {
					goto yy28
				}
			} else {
				goto yy48
			}
		yy52:
			s.cursor += 1
			yych = s.text[s.cursor]
			if yych <= ',' {
				if yych == '+' {
					goto yy57
				}
				goto yy51
			} else {
				if yych <= '-' {
					goto yy57
				}
				if yych <= '/' {
					goto yy51
				}
				if yych <= '9' {
					goto yy58
				}
				goto yy51
			}
		yy53:
			s.cursor += 1
			yych = s.text[s.cursor]
			if yych == 'd' {
				goto yy60
			}
			goto yy36
		yy54:
			s.cursor += 1
			yych = s.text[s.cursor]
			if yych == 'p' {
				goto yy61
			}
			goto yy36
		yy55:
			s.cursor += 1
			yych = s.text[s.cursor]
			if yych == 't' {
				goto yy62
			}
			goto yy36
		yy56:
			s.cursor += 1
			yych = s.text[s.cursor]
			if yych == 'u' {
				goto yy63
			}
			goto yy36
		yy57:
			s.cursor += 1
			yych = s.text[s.cursor]
			if yych <= '/' {
				goto yy51
			}
			if yych >= ':' {
				goto yy51
			}
		yy58:
			s.cursor += 1
			yych = s.text[s.cursor]
			if yych <= '/' {
				goto yy48
			}
			if yych <= '9' {
				goto yy58
			}
			goto yy48
		yy60:
			s.cursor += 1
			yych = s.text[s.cursor]
			if yych == 'u' {
				goto yy64
			}
			goto yy36
		yy61:
			s.cursor += 1
			yych = s.text[s.cursor]
			if yych == 'e' {
				goto yy65
			}
			goto yy36
		yy62:
			s.cursor += 1
			yych = s.text[s.cursor]
			if yych == 'u' {
				goto yy67
			}
			goto yy36
		yy63:
			s.cursor += 1
			yych = s.text[s.cursor]
			if yych == 'b' {
				goto yy68
			}
			goto yy36
		yy64:
			s.cursor += 1
			yych = s.text[s.cursor]
			if yych == 'l' {
				goto yy70
			}
			goto yy36
		yy65:
			s.cursor += 1
			yych = s.text[s.cursor]
			if yych <= 'Z' {
				if yych <= '/' {
					goto yy66
				}
				if yych <= '9' {
					goto yy35
				}
				if yych >= 'A' {
					goto yy35
				}
			} else {
				if yych <= '_' {
					if yych >= '_' {
						goto yy35
					}
				} else {
					if yych <= '`' {
						goto yy66
					}
					if yych <= 'z' {
						goto yy35
					}
				}
			}
		yy66:
			{
				tok = token.Pipe
				lit = "pipe"
				return
			}
		yy67:
			s.cursor += 1
			yych = s.text[s.cursor]
			if yych == 'r' {
				goto yy71
			}
			goto yy36
		yy68:
			s.cursor += 1
			yych = s.text[s.cursor]
			if yych <= 'Z' {
				if yych <= '/' {
					goto yy69
				}
				if yych <= '9' {
					goto yy35
				}
				if yych >= 'A' {
					goto yy35
				}
			} else {
				if yych <= '_' {
					if yych >= '_' {
						goto yy35
					}
				} else {
					if yych <= '`' {
						goto yy69
					}
					if yych <= 'z' {
						goto yy35
					}
				}
			}
		yy69:
			{
				tok = token.Stub
				lit = "stub"
				return
			}
		yy70:
			s.cursor += 1
			yych = s.text[s.cursor]
			if yych == 'e' {
				goto yy72
			}
			goto yy36
		yy71:
			s.cursor += 1
			yych = s.text[s.cursor]
			if yych == 'n' {
				goto yy74
			}
			goto yy36
		yy72:
			s.cursor += 1
			yych = s.text[s.cursor]
			if yych <= 'Z' {
				if yych <= '/' {
					goto yy73
				}
				if yych <= '9' {
					goto yy35
				}
				if yych >= 'A' {
					goto yy35
				}
			} else {
				if yych <= '_' {
					if yych >= '_' {
						goto yy35
					}
				} else {
					if yych <= '`' {
						goto yy73
					}
					if yych <= 'z' {
						goto yy35
					}
				}
			}
		yy73:
			{
				tok = token.Module
				lit = "module"
				return
			}
		yy74:
			s.cursor += 1
			yych = s.text[s.cursor]
			if yych <= 'Z' {
				if yych <= '/' {
					goto yy75
				}
				if yych <= '9' {
					goto yy35
				}
				if yych >= 'A' {
					goto yy35
				}
			} else {
				if yych <= '_' {
					if yych >= '_' {
						goto yy35
					}
				} else {
					if yych <= '`' {
						goto yy75
					}
					if yych <= 'z' {
						goto yy35
					}
				}
			}
		yy75:
			{
				tok = token.Return
				lit = "return"
				return
			}
		}

	}
}

func (s *Scanner) lexString(quote byte) (pos token.Pos, tok token.Token, lit string, err error) {
	var buf bytes.Buffer
	for {
		var u byte

		{
			var yych byte
			yych = s.text[s.cursor]
			if yych == '\n' {
				goto yy80
			}
			if yych == '\\' {
				goto yy82
			}
			s.cursor += 1
			{
				u = yych
				if u == quote {
					tok = token.String
					pos = token.Pos(s.token)
					lit = string(buf.Bytes())
					return
				}
				buf.WriteByte(u)
				continue
			}
		yy80:
			s.cursor += 1
		yy81:
			{
				err = ErrInvalidString
				return
			}
		yy82:
			s.cursor += 1
			yych = s.text[s.cursor]
			if yych <= 'b' {
				if yych <= '>' {
					if yych <= '"' {
						if yych <= '!' {
							goto yy81
						}
					} else {
						if yych == '\'' {
							goto yy85
						}
						goto yy81
					}
				} else {
					if yych <= '\\' {
						if yych <= '?' {
							goto yy87
						}
						if yych <= '[' {
							goto yy81
						}
						goto yy89
					} else {
						if yych <= '`' {
							goto yy81
						}
						if yych <= 'a' {
							goto yy91
						}
						goto yy93
					}
				}
			} else {
				if yych <= 'q' {
					if yych <= 'f' {
						if yych <= 'e' {
							goto yy81
						}
						goto yy95
					} else {
						if yych == 'n' {
							goto yy97
						}
						goto yy81
					}
				} else {
					if yych <= 't' {
						if yych <= 'r' {
							goto yy99
						}
						if yych <= 's' {
							goto yy81
						}
						goto yy101
					} else {
						if yych == 'v' {
							goto yy103
						}
						goto yy81
					}
				}
			}
			s.cursor += 1
			{
				buf.WriteByte('"')
				continue
			}
		yy85:
			s.cursor += 1
			{
				buf.WriteByte('\'')
				continue
			}
		yy87:
			s.cursor += 1
			{
				buf.WriteByte('?')
				continue
			}
		yy89:
			s.cursor += 1
			{
				buf.WriteByte('\\')
				continue
			}
		yy91:
			s.cursor += 1
			{
				buf.WriteByte('\a')
				continue
			}
		yy93:
			s.cursor += 1
			{
				buf.WriteByte('\b')
				continue
			}
		yy95:
			s.cursor += 1
			{
				buf.WriteByte('\f')
				continue
			}
		yy97:
			s.cursor += 1
			{
				buf.WriteByte('\n')
				continue
			}
		yy99:
			s.cursor += 1
			{
				buf.WriteByte('\r')
				continue
			}
		yy101:
			s.cursor += 1
			{
				buf.WriteByte('\t')
				continue
			}
		yy103:
			s.cursor += 1
			{
				buf.WriteByte('\v')
				continue
			}
		}

	}
}
